#!/usr/bin/env bash
# wrapper.sh - install/verify/uninstall the streaming_client compatibility
# wrapper. This is the only module that writes inside the Steam directory.
#
# Invariants this module maintains:
#  - streaming_client.real is always Valve's untouched ELF binary.
#  - streaming_client is either Valve's untouched ELF binary (not yet
#    patched) or our wrapper script carrying WRAPPER_MARKER.
#  - The wrapper never execs a file that resolves to itself (recursion guard,
#    both at install time and inside the generated script).
#  - Nothing is ever deleted without first being copied into $BACKUP_DIR.

WRAPPER_SCHEMA_VERSION=1

render_env_conf() {
    local apply_x11="$1"
    cat <<EOF
# Managed by steam-remoteplay-wayland-fix (state.env / doctor / repair keep
# this in sync). Safe to hand-edit for experimentation; 'repair' only
# rewrites the keys below, it will not add new ones on its own.
APPLY_X11_WORKAROUND=${apply_x11}
STRIP_STEAM_OVERLAY=yes
CLEAR_LD_PRELOAD=yes
EOF
}

render_wrapper_script() {
    local apply_x11_default="$1"
    cat <<'EOF'
#!/usr/bin/env bash
WRAPPER_MARKER_LINE
WRAPPER_VERSION_LINE
#
# This file replaces Steam's real streaming_client binary. The untouched
# original is preserved next to it as streaming_client.real.
#
# Project: https://github.com/Carsico00/steam-remoteplay-wayland-fix
# What/why: docs/architecture.md ("FIX vs WORKAROUND" classification).
#
# Do not edit this file by hand - `repair`/`install` regenerate it. Runtime
# behaviour is controlled by env.conf, sourced below.

set -u

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_real="$_here/streaming_client.real"
_env_conf="$HOME/.config/steam-remoteplay-wayland-fix/env.conf"

if [[ -e "$_real" ]]; then
    if [[ "$(readlink -f "$_real" 2>/dev/null)" == "$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null)" ]]; then
        echo "steam-remoteplay-wayland-fix: refusing to exec self (recursion guard tripped)" >&2
        exit 70
    fi
else
    echo "steam-remoteplay-wayland-fix: streaming_client.real is missing next to the wrapper." >&2
    echo "Run: steam-remoteplay-wayland-fix repair" >&2
    exit 71
fi

APPLY_X11_WORKAROUND=WRAPPER_DEFAULT_APPLY_X11
STRIP_STEAM_OVERLAY=yes
CLEAR_LD_PRELOAD=yes
# shellcheck source=/dev/null
[[ -f "$_env_conf" ]] && source "$_env_conf"

args=()
for arg in "$@"; do
    if [[ "$STRIP_STEAM_OVERLAY" == "yes" && "$arg" == "-steam-overlay" ]]; then
        continue
    fi
    args+=("$arg")
done

if [[ "$CLEAR_LD_PRELOAD" == "yes" ]]; then
    unset LD_PRELOAD
fi

if [[ "$APPLY_X11_WORKAROUND" == "yes" ]]; then
    export SDL_VIDEO_DRIVER=x11
    export SDL_VIDEODRIVER=x11
    export EGL_PLATFORM=x11
    unset WAYLAND_DISPLAY
fi

exec "$_real" "${args[@]}"
EOF
}

# Materializes the wrapper template with the marker/version/default baked in.
_render_wrapper_final() {
    local apply_x11_default="$1"
    render_wrapper_script "$apply_x11_default" \
        | sed \
            -e "s|WRAPPER_MARKER_LINE|${WRAPPER_MARKER}|" \
            -e "s|WRAPPER_VERSION_LINE|${WRAPPER_VERSION_TAG_PREFIX} ${WRAPPER_SCHEMA_VERSION}|" \
            -e "s|WRAPPER_DEFAULT_APPLY_X11|${apply_x11_default}|"
}

wrapper_installed_version() {
    local path="$1"
    [[ -f "$path" ]] || return 1
    grep -F "$WRAPPER_VERSION_TAG_PREFIX" "$path" 2>/dev/null | head -n1 | awk '{print $NF}'
}

# install_wrapper -> 0 on success, sets SRWF_LAST_ACTION for the caller to log.
install_wrapper() {
    local client real apply_x11
    client=$(streaming_client_path) || { log_fail "Steam installation not found (no ubuntu12_64/ directory)."; return 1; }
    real=$(streaming_client_real_path)

    if [[ ! -e "$client" ]]; then
        log_fail "streaming_client not found at $client."
        log_line "        Launch Remote Play once from Steam so it downloads app 202355, then retry."
        return 1
    fi

    if needs_nvidia_wayland_workaround; then apply_x11="yes"; else apply_x11="no"; fi

    local cur_has_marker=0 cur_is_elf=0 real_ok=0
    has_marker "$client" && cur_has_marker=1
    is_elf "$client" && cur_is_elf=1
    { [[ -f "$real" ]] && is_elf "$real"; } && real_ok=1

    ensure_dirs

    if [[ "$cur_has_marker" == "1" ]]; then
        if [[ "$real_ok" != "1" ]]; then
            log_fail "Wrapper is installed but streaming_client.real is missing or corrupt."
            log_line "        This should not happen from normal use; restore from backup with:"
            log_line "        steam-remoteplay-wayland-fix repair --force-reset (see docs/troubleshooting.md)"
            return 1
        fi
        _write_wrapper_files "$client" "$apply_x11"
        log_ok "Wrapper already installed; refreshed to current version/policy."
        return 0
    fi

    if [[ "$cur_is_elf" == "1" && "$real_ok" != "1" ]]; then
        # First install, or Steam replaced our wrapper with a fresh original binary on update.
        backup_create pristine-real "$client" >/dev/null
        mv "$client" "$real"
        _write_wrapper_files "$client" "$apply_x11"
        log_ok "Original streaming_client preserved as streaming_client.real; wrapper installed."
        return 0
    fi

    if [[ "$cur_is_elf" == "1" && "$real_ok" == "1" ]]; then
        if [[ "$(sha256_of "$client")" == "$(sha256_of "$real")" ]]; then
            _write_wrapper_files "$client" "$apply_x11"
            log_ok "Wrapper installed (streaming_client.real already present and matching)."
            return 0
        fi
        if [[ "$(state_get wrapper_installed)" == "1" ]]; then
            # We previously installed the wrapper (recorded in our own state).
            # streaming_client being a *different* ELF now than our recorded
            # streaming_client.real means Steam shipped a new build over our
            # wrapper during an update. The new file is the new authoritative
            # original; our old .real is superseded, not "the truth".
            log_warn "Steam updated streaming_client since our last install (build changed)."
            backup_create pristine-real "$client" >/dev/null
            mv "$client" "$real"
            _write_wrapper_files "$client" "$apply_x11"
            log_ok "streaming_client.real refreshed to the new Steam build; wrapper reapplied."
            return 0
        fi
        log_fail "streaming_client and streaming_client.real are both original binaries but differ."
        log_line "        Refusing to guess which one is authoritative. See: steam-remoteplay-wayland-fix status"
        return 1
    fi

    if [[ "$cur_is_elf" != "1" && "$cur_has_marker" != "1" ]]; then
        if [[ "$real_ok" == "1" ]]; then
            log_warn "A non-Steam, non-${APP_NAME} script is already at streaming_client. Backing it up before replacing it."
            backup_create foreign-wrapper "$client" >/dev/null
            backup_has pristine-real || backup_create pristine-real "$real" >/dev/null
            _write_wrapper_files "$client" "$apply_x11"
            log_ok "Foreign wrapper backed up and replaced. streaming_client.real left untouched."
            return 0
        fi
        log_fail "Unrecognized file at $client and no streaming_client.real to fall back to."
        log_line "        Verify Steam files integrity (Steam > right-click game > Properties >"
        log_line "        Installed Files > Verify integrity) and re-run install."
        return 1
    fi

    log_fail "Unexpected state at $client; refusing to modify it. See: steam-remoteplay-wayland-fix status"
    return 1
}

_write_wrapper_files() {
    local client="$1" apply_x11="$2"
    _render_wrapper_final "$apply_x11" > "$client.tmp"
    chmod +x "$client.tmp"
    mv "$client.tmp" "$client"
    render_env_conf "$apply_x11" > "$ENV_CONF"
    state_set wrapper_installed "1"
    state_set wrapper_version "$WRAPPER_SCHEMA_VERSION"
    state_set apply_x11_workaround "$apply_x11"
    state_set streaming_client_path "$client"
    state_set streaming_client_real_path "$(streaming_client_real_path)"
    state_set streaming_client_real_sha256 "$(sha256_of "$(streaming_client_real_path)")"
    state_set last_install_steam_build "$(detect_steam_build_id 2>/dev/null || true)"
    state_set last_install_timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}

# wrapper_status -> prints one of:
#   not-installed | active | stale-overwritten | foreign | corrupt
wrapper_status() {
    local client real
    client=$(streaming_client_path 2>/dev/null) || { echo "not-installed"; return; }
    real=$(streaming_client_real_path 2>/dev/null)

    if [[ ! -e "$client" ]]; then
        echo "not-installed"
        return
    fi
    if has_marker "$client"; then
        if [[ -f "$real" ]] && is_elf "$real"; then
            echo "active"
        else
            echo "corrupt"
        fi
        return
    fi
    if is_elf "$client"; then
        if [[ -f "$real" ]] || [[ "$(state_get wrapper_installed)" == "1" ]]; then
            echo "stale-overwritten"   # Steam update replaced our wrapper
        else
            echo "not-installed"
        fi
        return
    fi
    # Not ELF, no marker: some other script is sitting at streaming_client.
    if [[ -f "$real" ]] && is_elf "$real"; then
        echo "foreign"   # recoverable: install_wrapper backs it up and replaces it
    else
        echo "corrupt"   # unrecognized script AND no original to fall back to
    fi
}

# uninstall_wrapper -> restores Valve's pristine binary as streaming_client
# and removes streaming_client.real + our generated env.conf.
uninstall_wrapper() {
    local client real
    client=$(streaming_client_path) || { log_warn "Steam installation not found; nothing to uninstall."; return 0; }
    real=$(streaming_client_real_path)

    if [[ -f "$real" ]] && is_elf "$real"; then
        cp -p "$real" "$client.tmp"
        chmod +x "$client.tmp"
        mv "$client.tmp" "$client"
        rm -f "$real"
        rm -f "$ENV_CONF"
        state_set wrapper_installed "0"
        log_ok "Restored Valve's original streaming_client and removed the wrapper."
        return 0
    fi

    if backup_restore_pristine "$client"; then
        log_ok "Restored streaming_client from backup (streaming_client.real was already gone)."
        return 0
    fi

    log_fail "No streaming_client.real and no usable backup found; cannot safely restore."
    return 1
}

backup_restore_pristine() {
    restore_from_backup pristine-real "$1"
}
